import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import terminalStyles from '../styles/terminal.module.css'
import { BashInterPriter } from '../src/interpriter/interpriter'
// import {browserName,osName} from 'react-device-detect'

const Home: NextPage = () => {


  const inputForm = useRef<null | HTMLInputElement>(null);
  useEffect(() => {
    inputForm.current?.focus();
  }, [inputForm]);

  const [logs, setLogs] = useState<any[]>([]);
  // const [loadingText,setLoadingText]=useState<string>('');
  
  
 
  const stdout = (msg: string) => {
    console.log('stdout_log->', msg);

    const m = msg.split('\n').map((line) => {
      return <p>{line}</p>
    });
    // console.log(m);
    setLogs(
      (beforeValues) => [...beforeValues, ...m]
    );
  }


  const stderr = (msg: string) => {
    console.log('std_err->'+msg);
    setLogs(
      (beforeValues) => [...beforeValues, <p className="text-red-500">{msg}</p>]
      
    );
  }

  const stdin = () => {
    
  };


  const onInputKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      const promptStr = '';

      setLogs((beforeValues) => { return [...beforeValues, promptStr + command] });

      setCommandHostories([command, ...commandHistories]);

      Exefunc(command);
      
      setCommand('');
      setCurrentLogNumber(0);
    }
    
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'></link>
        {/* <link href="https://fonts.googleapis.com/css2?family=Space+Mono&display=swap" rel="stylesheet"></link> */}
      </Head>
      <style jsx>{`
      .output::-webkit-scrollbar{
        width:5px;
        
        
      }
      @font-face {
        font-family: 'hackgen';
        src: url('/font/HackGen35ConsoleNF-Regular.ttf') format('truetype');
        
      }
      .output{
        font-family: 'hackgen', monospace;
      }
      ::-webkit-scrollbar-thumb {
        background: grey;
        
        border-radius: 5px;
      }
      @media screen and (max-width: 768px) {
        .window{
          width:95vw;
          height:90%;    
        }
      }
      .window{
        min-width: 80vw;
        // height:100%;
      }
    `}</style>
      <div className='bg-black'>
       
            <div role="terminal" className="flex flex-col h-full px-2 overflow-scroll text-white bg-scroll bg-black rounded-b-lg output" >


              
              {logs.map((value, index) => {
                return <div key={index} className={terminalStyles.log}>{value}</div>
              })}

              <div className="">
                <p className='inline'><i className={"text-orange-400"}>{bashInterPriter.getCurentUser()}</i>@{'anonymous'}:{bashInterPriter.getCwd()}{"$"} </p>
                <input ref={inputForm} value={command} onChange={onInputChange} onKeyDown={onInputKeyDown} type={'text'} className="inline px-0 text-white bg-black border-none focus:outline-none" />
                {/* <div className='w-1 px-1 animate-ping'></div> */}
              </div>
            </div>
          </div>

        </div>
  )
}

export default Home
